#ifndef WIDGETSUIFRAME_GLOBAL_H
#define WIDGETSUIFRAME_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(WIDGETSUIFRAME_LIBRARY)
#define WIDGETSUIFRAME_EXPORT Q_DECL_EXPORT
#else
#define WIDGETSUIFRAME_EXPORT Q_DECL_IMPORT
#endif

#endif // WIDGETSUIFRAME_GLOBAL_H
