#ifndef WIDGETUIFRAME_GLOBAL_H
#define WIDGETUIFRAME_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(WIDGETUIFRAME_LIBRARY)
#define WIDGETUIFRAME_EXPORT Q_DECL_EXPORT
#else
#define WIDGETUIFRAME_EXPORT Q_DECL_IMPORT
#endif

#endif // WIDGETUIFRAME_GLOBAL_H
